version: '2'

services:

    client:
        image: node
        command: bash -c "cd /app && yarn install --ignore-engines && yarn start"
        volumes:
            - ./testngapp:/app
        ports: 
            - "4200:4200"