version: '3'
services:
  ngserve:
    image: node
    command: bash -c "cd /app && yarn install --ignore-engines && yarn global add @angular/cli && yarn start"
    volumes:
        - ./testngapp:/app
    ports: 
        - "4200:4200"